version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: gm3a-nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-gm3a
    networks:
      - gm3a-network

  web-gm3a:
    build: .
    container_name: gm3a-container
    restart: always
    #ports:
     # - "8082:80"
    networks:
      - gm3a-network

# --- MONITORING SERVICES MULAI DARI SINI ---

  prometheus:
    image: prom/prometheus:latest
    container_name: gm3a-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    #  ports:
      # - "9090:9090"
    networks:
      - gm3a-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: gm3a-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    # ports:
      # - "9100:9100"
    networks:
      - gm3a-network

  grafana:
    image: grafana/grafana:latest
    container_name: gm3a-grafana
    restart: unless-stopped
    # ports:
      # - "3000:3000" # Port Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password default, nanti ganti
      - GF_SERVER_ROOT_URL=http://localhost:8082/monitoring/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - gm3a-network

# --- JANGAN LUPA DEFINISIKAN NETWORK & VOLUME DI PALING BAWAH ---
networks:
  gm3a-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
