global:
  scrape_interval: 15s # Ambil data setiap 15 detik

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter' # Ini mata-mata laptop kita
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100'] # Mengarah ke container node-exporter
