name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Trigger setiap kali ada push ke branch main

jobs:
  deploy:
    runs-on: self-hosted # PENTING: Ini memerintahkan jalan di laptopmu
    
    steps:
      - name: Ambil kode terbaru
        uses: actions/checkout@v3

      - name: Matikan container lama (jika ada)
        # "|| true" agar tidak error jika container belum ada (deploy pertama)
        run: docker compose down || true

      - name: Build dan Jalankan container baru
        run: docker compose up -d --build

      - name: Bersihkan image sampah
        run: docker image prune -f
